name: CI

on:
  push:
      branches:
          - master
  pull_request:
      branches:
          - master
jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: melodic
            ROS_REPO: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - name: run script
        run: |
            source /opt/ros/melodic/setup.bash
            source /root/target_ws/devel/setup.bash

